<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="SimpleInjector" Version="5.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameVisionTool.Common.Domain\GameVisionTool.Common.Domain.csproj" />
    <ProjectReference Include="..\GameVisionTool.Common.Validation\GameVisionTool.Common.Validation.csproj" />
    <ProjectReference Include="..\GameVisionTool.Messages\GameVisionTool.Messages.csproj" />
  </ItemGroup>

</Project>
