using GameVisionTool.Integration.GoogleGemini.ClientConfiguration;
using Google.GenAI.Types;

namespace GameVisionTool.Integration.GoogleGemini.Agents;

public class GoogleGeminiAgentResponseGenerator(GeminiClientBuilder geminiClientBuilder) : IGoogleGeminiAgent
{
    public async Task<string> GenerateResponse(
        string apiKey, 
        string model,
        int maxOutputTokens, 
        string systemInstructions, 
        ThinkingLevel thinkingLevel,
        string userMessage, 
        ConversationTurn[] history)
    {
        var client = geminiClientBuilder.GetClient(apiKey);
        
        // Generate the client config with using the supplied System Instructions
        var clientConfig = new GenerateContentConfig
        {
            MaxOutputTokens = maxOutputTokens,
            ThinkingConfig = new ThinkingConfig { ThinkingLevel = thinkingLevel },
            SystemInstruction = new Content
            {
                Parts = [Part.FromText(systemInstructions)],
            },
        };
        
        // Prior turns first, then the current step prompt as the user turn. Blank turns are skipped
        // so an empty first-turn input (relying on a per-step default) can't produce an empty Content.
        var contents = history
            .Where(turn => !string.IsNullOrWhiteSpace(turn.Text))
            .Select(turn => new Content
            {
                Role = turn.Role.ToGeminiRole(),
                Parts = [Part.FromText(turn.Text)],
            })
            .ToList();

        contents.Add(new Content
        {
            Role = ConversationRole.User.ToGeminiRole(),
            Parts = [Part.FromText(userMessage)],
        });

        var response = await client.GenerateAgentResponse(model, contents, clientConfig);

        // Pattern check rather than string.IsNullOrEmpty: netstandard2.0's reference assembly carries no
        // [NotNullWhen(false)] annotation, so only the pattern narrows `response` to non-null below.
        if (response is null or "")
        {
            throw new InvalidOperationException("No backstory generated by the backstory writer.");
        }

        return response;
    }
}