using GameVisionTool.Integration.GoogleGemini.ClientConfiguration;
using Google.GenAI.Types;

namespace GameVisionTool.Integration.GoogleGemini.Agents;

public class ScienceFictionBackstoryAgent(GeminiClientBuilder geminiClientBuilder) : IGoogleGeminiAgent
{
    private const string Model = "gemini-3.6-flash";
    private const int MaxOutputTokens = 2048;
    private static readonly ThinkingLevel Thinking = ThinkingLevel.Minimal;

    public async Task<string> GenerateResponse(string apiKey, string userMessage, ClientParameters clientParams, ConversationTurn[] history)
    {
        var client = geminiClientBuilder.GetClient(apiKey);

        var stepPrompt = BuildPrompt(userMessage);

        // No string.Format: the template carries no placeholders, and formatting it would only turn a
        // stray brace in the prose into a FormatException at runtime.
        var systemInstruction = GetSystemPromptTemplate();

        // Temperature/TopP/TopK are deprecated and ignored on Gemini 3.x, and will be rejected outright
        // by future models — response style is steered through the system instruction instead.
        var clientConfig = new GenerateContentConfig
        {
            MaxOutputTokens = MaxOutputTokens,
            ThinkingConfig = new ThinkingConfig { ThinkingLevel = Thinking },
            SystemInstruction = new Content
            {
                Parts = [Part.FromText(systemInstruction)],
            },
        };

        // Prior turns first, then the current step prompt as the user turn. Blank turns are skipped
        // so an empty first-turn input (relying on a per-step default) can't produce an empty Content.
        var contents = history
            .Where(turn => !string.IsNullOrWhiteSpace(turn.Text))
            .Select(turn => new Content
            {
                Role = turn.Role.ToGeminiRole(),
                Parts = [Part.FromText(turn.Text)],
            })
            .ToList();

        contents.Add(new Content
        {
            Role = ConversationRole.User.ToGeminiRole(),
            Parts = [Part.FromText(stepPrompt)],
        });

        var response = await client.GenerateAgentResponse(Model, contents, clientConfig);

        // Pattern check rather than string.IsNullOrEmpty: netstandard2.0's reference assembly carries no
        // [NotNullWhen(false)] annotation, so only the pattern narrows `response` to non-null below.
        if (response is null or "")
        {
            throw new InvalidOperationException("No backstory generated by the backstory writer.");
        }

        return response;
    }

    // Builds the user turn: the writer's brief wrapped in the craft expectations that apply to every
    // backstory, with an open-ended default when the brief is blank. The persona and the standing style
    // rules live in the system instruction instead, so they are re-applied on every turn of a revision.
    private static string BuildPrompt(string userPrompt) =>
        $"""
         Write science fiction backstory to the brief below.

         Brief: "{DefaultIfBlank(userPrompt, "Invent a character of your own choosing and write their backstory. Pick the setting, era and technology level yourself, and commit to them.")}"

         Work to these expectations unless the brief overrides them:
         - Establish the world through what it costs someone to live in it — the work, the air, the light, the price of something ordinary — not through a history lesson.
         - Give the subject an origin, one formative event that divides their life into before and after, and something it cost them that they cannot get back.
         - Name things. Places, factions, ships, slang, hardware. Use invented terms in context and leave them unexplained where the meaning is clear.
         - Decide what the technology can and cannot do, then honour that limit for the rest of the piece.
         - Leave two or three threads unfinished — a debt, a rumour that is half true, someone still looking for them — that the game can pull on later.
         - Aim for 400-600 words unless the brief asks for a different length.
         """;

    private static string DefaultIfBlank(string value, string fallback) =>
        string.IsNullOrWhiteSpace(value) ? fallback : value;

    private static string GetSystemPromptTemplate()
    {
        return """
               You are an award-winning science fiction novelist and worldbuilder, writing character and world backstory for a video game.

               Write like a novelist, not like a wiki. Favour scene, sensory detail and specific invented proper nouns over summary and exposition; reveal character through what someone does and what they refuse to do. One concrete detail earns more than a paragraph of explanation.

               Keep the world's rules. Technology behaves consistently, costs something to use, and has limits you honour once you have stated them. Treat everything established earlier in this conversation as canon: never contradict a name, date or detail you have already committed to, and when the writer asks for a change, revise the existing draft rather than starting a new one.

               Avoid the tired furniture of the genre: prophecies and chosen ones, "little did they know", dead-family backstory with no consequence, and technology that conveniently solves the plot. Avoid purple prose and adverb-heavy melodrama — plain, concrete sentences carry the weight, and the one lyrical line is earned by keeping the rest lean.

               Format as prose in simple Markdown: short paragraphs, a "###" header only where a section genuinely needs one, bullets only for lists that are actually lists. Respect any length the writer asks for. Return only the story text — no preamble, no summary of what you wrote, no notes on your own choices, no offers to continue.
               """;
    }
}
